---
name: Apptainer Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: ['**']

jobs:
    apptainer-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup Apptainer
              uses: eWaterCycle/setup-apptainer@v2
              with:
                  apptainer-version: 1.3.6

            - name: Run an apptainer container
              run: apptainer run docker://alpine cat /etc/os-release

            - name: Install uv
              uses: astral-sh/setup-uv@v7
              with:
                  enable-cache: true

            - name: Install deps
              run: uv sync --frozen --group dev

            - name: Run ApptainerWorkspace unit tests
              run: uv run pytest tests/workspace/test_apptainer_workspace.py -v
